import { ScanData } from '../types/scan';

const SIMULATED_OBJECTS: Record<string, Partial<ScanData>> = {
  'APPLE': {
    objectName: 'MALUS_DOMESTICA',
    confidence: '99.4%',
    subjectId: 'ORG_332_FL',
    classification: 'Deciduous pomaceous fruit-bearing tree of the rose family. Highly cultivated for its edible sweet pome fruit.',
    facts: [
      'Apples originated in Central Asia, specifically the wild Malus sieversii.',
      'There are over 7,500 known cultivars of apples worldwide.',
      'The fruit is rich in malic acid and pectin, contributing to its structural firmness.',
      'Apples account for nearly 50% of the worldwide deciduous fruit tree production.',
      'An apple floats in water because it consists of 25% air.'
    ],
    relatedScans: [
      { timestamp: '2024.01.12 09:15', objectName: 'CRIMSON_PEAR_09' },
      { timestamp: '2024.02.04 14:22', objectName: 'WILD_BERRY_LOG' },
      { timestamp: '2024.03.18 11:04', objectName: 'ORCHARD_MAPPING' }
    ]
  },
  'CAMERA': {
    objectName: 'OPTICAL_IMAGE_RECORDER',
    confidence: '98.1%',
    subjectId: 'TEC_881_OBJ',
    classification: 'Optical instrument used to capture images. In its simplest form, it consists of a light-proof box with an aperture.',
    facts: [
      'The first permanent photograph was taken in 1826 by Joseph Nicéphore Niépce.',
      'The word "camera" comes from "camera obscura," meaning "dark chamber."',
      'Modern digital sensors use Bayer filters to interpolate color from monochromatic photosites.',
      'The largest camera ever built utilized a 3.2-gigapixel sensor for deep space observation.',
      'Digital cameras capture light using a charge-coupled device (CCD) or CMOS sensor.'
    ],
    relatedScans: [
      { timestamp: '2023.11.02 10:10', objectName: 'FILM_CANISTER_7' },
      { timestamp: '2023.12.14 16:45', objectName: 'LENS_CAP_SMALL' },
      { timestamp: '2024.01.20 08:30', objectName: 'DARKROOM_ARCHIVE' }
    ]
  }
};

export async function simulateScan(query: string): Promise<ScanData> {
  // Artificial delay to mimic scanning
  await new Promise(resolve => setTimeout(resolve, 1500));

  const upperQuery = query.toUpperCase();
  const baseData = SIMULATED_OBJECTS[upperQuery] || {
    objectName: upperQuery.replace(/\s+/g, '_') + '_SIMULATED',
    confidence: (94 + Math.random() * 5).toFixed(1) + '%',
    subjectId: 'SIM_' + Math.random().toString(36).substr(2, 5).toUpperCase(),
    classification: `SIMULATED_DATA: The system has generated a synthetic profile for ${query}. Clinical observation suggests a unique structural composition.`,
    facts: [
      `A typical ${query} exhibits high structural integrity.`,
      `Initial analysis suggests a localized origin for this specific unit.`,
      `Thermal and spectral signatures are within expected archival parameters.`,
      `Cultural significance of ${query} varies by geographical sector.`,
      `This is a synthetic data record generated by the SCAN_ARCHIVE offline module.`
    ],
    relatedScans: [
      { timestamp: '2024.03.11 08:00', objectName: 'SIM_RECORD_A' },
      { timestamp: '2024.03.12 09:15', objectName: 'SIM_RECORD_B' },
      { timestamp: '2024.03.13 14:22', objectName: 'SIM_RECORD_C' }
    ]
  };

  return {
    isVague: false,
    ...baseData,
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1000&auto=format&fit=crop' // Generic high-quality abstract tech image
  };
}
